name: Build Toolchains with crosstool-ng

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
    contents: write

env:
  CT_NG_REF: 32f288e61fee8528931bcd55bf106cf0cfb4e2a1
  PLATFORM: "linux-amd64"

jobs:
  build-toolchains:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: avr
          - toolchain: lm32-unknown-elf
          - toolchain: loongarch64-unknown-elf
          - toolchain: m68k-unknown-elf
          - toolchain: rx-zephyr-elf
          - toolchain: or1k-unknown-elf
          - toolchain: msp430-unknown-elf
          - toolchain: sh-unknown-elf

    steps:
      - uses: actions/checkout@v4

      - name: "prereq Linux"
        run: |
          sudo apt-get install -y gperf help2man libtool-bin

      - uses: actions/checkout@v4
        with:
          repository: crosstool-ng/crosstool-ng
          ref: ${{ env.CT_NG_REF }}
          path: crosstool-ng

      - name: "Apply patches"
        run: |
          cd crosstool-ng
          if [ -d "${{ github.workspace }}/patches/crosstool-ng" ] && [ "$(ls -A ${{ github.workspace }}/patches/crosstool-ng)" ]; then
            git apply ${{ github.workspace }}/patches/crosstool-ng/*.patch
          fi

      - name: Build crosstool-ng
        run: |
          cd crosstool-ng
          ./bootstrap
          ./configure --prefix="${{ github.workspace }}/.local/"
          make
          make install
          echo "${{ github.workspace }}/.local/bin" >> "$GITHUB_PATH"

      - name: Build toolchain
        run: |
          mkdir -p src
          export CONFIG_=CT_
          ./scripts/merge_config.sh -m ./configs/crosstool-ng/${{ matrix.toolchain }} ./configs/crosstool-ng/local.config
          ct-ng defconfig DEFCONFIG=.config
          ct-ng show-config
          ct-ng build V=2

      - name: Pack toolchain tarball
        run: |
          tar -C ${{ github.workspace }}/x-tools \
              -cvf ${{ matrix.toolchain }}.${{ env.PLATFORM }}.tar.xz ${{ matrix.toolchain }}

      - name: Upload toolchain tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.toolchain }}.${{ env.PLATFORM }}.tar.xz
          path: ${{ matrix.toolchain }}.${{ env.PLATFORM }}.tar.xz

      - name: upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.toolchain }}.${{ env.PLATFORM }}.log
          path: |
            build.log
            .config

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.toolchain }}.${{ env.PLATFORM }}.tar.xz
